// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: ["src/main.ts", "src/index.ts"],
    project: ["src/**/*.{ts,vue}"],
    ignoreDependencies: [
        // WHY: referenced in CSS @import, not detectable by knip
        "@adddog/design-tokens",
        "@adddog/tailwind-theme",
        // WHY: peerDep — used by consuming apps, not directly in src
        "@internationalized/date",
        // WHY: build tooling deps used in vite/postcss config, not in src
        "@tailwindcss/container-queries",
        "@tailwindcss/vite",
        "@vitejs/plugin-vue",
        "tailwindcss-animate",
        "tailwindcss",
        "tw-animate-css",
        "unbuild",
    ],
    // WHY: referenced in tsconfig types, not in source imports
    ignoreUnresolved: ["vitest/globals"],
    ignore: [
        // WHY: standalone example app, not part of library src
        "example-app/**",
    ],
});
