// Generated by monorepo-scripts/generate-knip-config.mts
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "../../monorepo-scripts/knip-defaults.js";

export default defineKnipConfig({
    entry: ["src/main.ts", "src/index.ts"],
    project: ["src/**/*.{ts,vue}"],
    ignoreDependencies: [
        "@adddog/design-tokens",
        "@internationalized/date",
        "@tailwindcss/container-queries",
        "@tailwindcss/vite",
        "@vitejs/plugin-vue",
        "tailwindcss-animate",
        "tailwindcss",
        "unbuild",
    ],
    ignoreUnresolved: ["vitest/globals"],
    ignore: [
        "example-app/**",
        "src/style/css/themes/**",
    ],
});
